# Generated by Django 2.2.8 on 2020-03-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20200320_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='profile_pics'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='status',
            field=models.TextField(),
        ),
    ]
