# Generated by Django 2.2.8 on 2020-03-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_auto_20200321_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='header_image',
            field=models.ImageField(default='', upload_to='post_uploads'),
            preserve_default=False,
        ),
    ]
